version: '3.8'

services:
  db:
    image: postgres:13
    container_name: makeup_db
    environment:
      POSTGRES_DB: makeup_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alexandrina
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: flask_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:alexandrina@db:5432/makeup_db
      - DB_HOST=db
      - DB_NAME=makeup_db
      - DB_USER=postgres
      - DB_PASSWORD=alexandrina
      - DB_PORT=5432
    ports:
      - "5000:5000"
      - "8001:8001"
    volumes:
      - ./:/app
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge